# Generated by Django 3.1.3 on 2020-11-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CastClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=192, unique=True, verbose_name='名前')),
                ('en_name', models.CharField(max_length=192, unique=True, verbose_name='名前')),
                ('point', models.IntegerField(default=0, verbose_name='しきい値')),
            ],
        ),
        migrations.CreateModel(
            name='GuestLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=192, unique=True, verbose_name='名前')),
                ('en_name', models.CharField(max_length=192, unique=True, verbose_name='名前')),
                ('point', models.IntegerField(default=0, verbose_name='しきい値')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_footprint', models.BooleanField(default=True, verbose_name='app_footprint')),
                ('app_tweetlike', models.BooleanField(default=True, verbose_name='app_tweetlike')),
                ('app_autodelay', models.BooleanField(default=True, verbose_name='app_autodelay')),
                ('app_autocharge', models.BooleanField(default=True, verbose_name='app_autocharge')),
                ('app_autoremove', models.BooleanField(default=True, verbose_name='app_autoremove')),
                ('email_footprint', models.BooleanField(default=True, verbose_name='email_footprint')),
                ('email_like', models.BooleanField(default=True, verbose_name='email_like')),
                ('email_message', models.BooleanField(default=True, verbose_name='email_message')),
                ('email_admin', models.BooleanField(default=True, verbose_name='email_admin')),
                ('email_join_leave', models.BooleanField(default=True, verbose_name='email_join_leave')),
                ('email_auto_delay', models.BooleanField(default=True, verbose_name='email_auto_delay')),
                ('email_tweet_like', models.BooleanField(default=True, verbose_name='email_tweet_like')),
                ('email_auto_charge', models.BooleanField(default=True, verbose_name='email_auto_charge')),
                ('email_auto_remove', models.BooleanField(default=True, verbose_name='email_auto_remove')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
    ]
