# Generated by Django 3.1.3 on 2020-12-22 19:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='static/image', verbose_name='バナー画像')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='static/image', verbose_name='メイン画像')),
                ('category', models.CharField(choices=[('u', '上表示'), ('m', '中表示'), ('d', '下表示'), ('n', '非表示')], default='u', max_length=2, verbose_name='カテゴリ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='CastClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=190, unique=True, verbose_name='名前')),
                ('en_name', models.CharField(blank=True, max_length=190, null=True, unique=True, verbose_name='英語名前')),
                ('color', models.CharField(blank=True, max_length=190, null=True, verbose_name='色')),
                ('point', models.IntegerField(default=0, verbose_name='しきい値')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('category', models.CharField(choices=[('s', 'situation'), ('r', 'request'), ('c', 'condition')], default='s', max_length=2, verbose_name='カテゴリ')),
                ('subcategory', models.CharField(blank=True, max_length=50, null=True, verbose_name='サブカテゴリ')),
                ('order', models.IntegerField(default=0, verbose_name='順序')),
                ('score', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='スコア')),
                ('call_shown', models.BooleanField(default=True, verbose_name='有効設定')),
                ('cast_shown', models.BooleanField(default=True, verbose_name='キャスト表示')),
                ('customer_shown', models.BooleanField(default=True, verbose_name='カスタマ項目')),
                ('sub_one', models.BooleanField(default=False, verbose_name='サブカテゴリ内単一設定')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='GuestLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=190, unique=True, verbose_name='名前')),
                ('en_name', models.CharField(blank=True, max_length=190, null=True, unique=True, verbose_name='名前')),
                ('point', models.IntegerField(default=0, verbose_name='しきい値')),
                ('color', models.CharField(blank=True, max_length=190, null=True, verbose_name='色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='会社名')),
                ('postal_code', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d\\d\\d-\\d\\d\\d\\d$')], verbose_name='郵便')),
                ('address', models.CharField(max_length=100, verbose_name='住所')),
                ('building', models.CharField(max_length=100, verbose_name='番地・建物名')),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d\\d-\\d\\d\\d\\d-\\d\\d\\d\\d$')], verbose_name='電話番号')),
                ('charger', models.CharField(max_length=20, verbose_name='担当者名')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_footprint', models.BooleanField(default=True, verbose_name='app_footprint')),
                ('app_tweetlike', models.BooleanField(default=True, verbose_name='app_tweetlike')),
                ('app_autodelay', models.BooleanField(default=True, verbose_name='app_autodelay')),
                ('app_autocharge', models.BooleanField(default=True, verbose_name='app_autocharge')),
                ('app_autoremove', models.BooleanField(default=True, verbose_name='app_autoremove')),
                ('ranking_display', models.BooleanField(default=True, verbose_name='ranking_display')),
                ('email_footprint', models.BooleanField(default=True, verbose_name='email_footprint')),
                ('email_like', models.BooleanField(default=True, verbose_name='email_like')),
                ('email_message', models.BooleanField(default=True, verbose_name='email_message')),
                ('email_admin', models.BooleanField(default=True, verbose_name='email_admin')),
                ('email_join_leave', models.BooleanField(default=True, verbose_name='email_join_leave')),
                ('email_auto_delay', models.BooleanField(default=True, verbose_name='email_auto_delay')),
                ('email_tweet_like', models.BooleanField(default=True, verbose_name='email_tweet_like')),
                ('email_auto_charge', models.BooleanField(default=True, verbose_name='email_auto_charge')),
                ('email_auto_remove', models.BooleanField(default=True, verbose_name='email_auto_remove')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=190, verbose_name='エリア')),
                ('shown', models.BooleanField(default=False, verbose_name='表示')),
                ('order', models.IntegerField(default=0, verbose_name='順序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basics.location', verbose_name='親エリア')),
            ],
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=75, size=[200, 200], upload_to='static/images', verbose_name='URI')),
                ('point', models.IntegerField(verbose_name='価格')),
                ('back', models.IntegerField(default=0, verbose_name='バック値')),
                ('is_shown', models.BooleanField(default=True, verbose_name='表示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basics.location', verbose_name='支店')),
            ],
        ),
        migrations.CreateModel(
            name='CostPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('cost', models.IntegerField(verbose_name='料金')),
                ('extend_cost', models.IntegerField(verbose_name='延長料金')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basics.location', verbose_name='支店')),
            ],
        ),
    ]
