# Generated by Django 3.1.3 on 2021-01-14 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptsetting',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='receiptsetting',
            name='postal_code',
            field=models.CharField(max_length=8, verbose_name='郵便'),
        ),
    ]
