# Generated by Django 3.1.3 on 2021-01-15 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0002_auto_20210114_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='castclass',
            name='order',
            field=models.IntegerField(default=0, verbose_name='順序'),
        ),
        migrations.AddField(
            model_name='guestlevel',
            name='order',
            field=models.IntegerField(default=0, verbose_name='順序'),
        ),
    ]
