# Generated by Django 3.1.3 on 2021-01-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0003_auto_20210115_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='costplan',
            name='classes',
            field=models.ManyToManyField(related_name='plans', to='basics.CastClass', verbose_name='キャスタレベル'),
        ),
        migrations.AddField(
            model_name='costplan',
            name='is_custom',
            field=models.BooleanField(default=False, verbose_name='カスタム'),
        ),
        migrations.AlterField(
            model_name='costplan',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='料金'),
        ),
        migrations.AlterField(
            model_name='costplan',
            name='extend_cost',
            field=models.IntegerField(default=0, verbose_name='延長料金'),
        ),
    ]
