# Generated by Django 3.1.3 on 2020-11-05 18:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0003_auto_20201105_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='castclass',
            name='color',
            field=models.CharField(blank=True, max_length=190, null=True, verbose_name='色'),
        ),
        migrations.AddField(
            model_name='castclass',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='作成日時'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='castclass',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AddField(
            model_name='guestlevel',
            name='color',
            field=models.CharField(blank=True, max_length=190, null=True, verbose_name='色'),
        ),
        migrations.AddField(
            model_name='guestlevel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='作成日時'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guestlevel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='castclass',
            name='en_name',
            field=models.CharField(blank=True, max_length=190, null=True, unique=True, verbose_name='英語名前'),
        ),
        migrations.AlterField(
            model_name='guestlevel',
            name='en_name',
            field=models.CharField(blank=True, max_length=190, null=True, unique=True, verbose_name='名前'),
        ),
    ]
