# Generated by Django 3.1.3 on 2020-11-06 05:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0004_auto_20201106_0221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('category', models.CharField(choices=[('s', 'situation'), ('r', 'request'), ('c', 'condition')], default='s', max_length=2, verbose_name='カテゴリ')),
                ('subcategory', models.CharField(default='', max_length=50, verbose_name='サブカテゴリ')),
                ('order', models.IntegerField(default=0, verbose_name='順序')),
                ('call_shown', models.BooleanField(default=True, verbose_name='有効設定')),
                ('cast_shown', models.BooleanField(default=True, verbose_name='キャスト表示')),
                ('customer_shown', models.BooleanField(default=True, verbose_name='カスタマ項目')),
                ('sub_one', models.BooleanField(default=False, verbose_name='サブカテゴリ内単一設定')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='会社名')),
                ('postal_code', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d\\d\\d-\\d\\d\\d\\d$')], verbose_name='')),
                ('address', models.CharField(max_length=100, verbose_name='住所')),
                ('building', models.CharField(max_length=100, verbose_name='番地・建物名')),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d\\d-\\d\\d\\d\\d-\\d\\d\\d\\d$')], verbose_name='電話番号')),
                ('charger', models.CharField(max_length=20, verbose_name='担当者名')),
            ],
        ),
    ]
