# Generated by Django 3.1.3 on 2020-11-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0006_choice_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='subcategory',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='サブカテゴリ'),
        ),
    ]
