# Generated by Django 3.1.3 on 2020-11-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0007_auto_20201106_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='subcategory',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='サブカテゴリ'),
        ),
    ]
