# Generated by Django 3.1.3 on 2020-11-06 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0008_auto_20201106_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptsetting',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d\\d-\\d\\d\\d\\d-\\d\\d\\d\\d$')], verbose_name='電話番号'),
        ),
    ]
