# Generated by Django 3.1.3 on 2020-11-06 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0009_auto_20201107_0306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='static/image', verbose_name='バナー画像')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='static/image', verbose_name='メイン画像')),
                ('category', models.CharField(choices=[('u', '上表示'), ('m', '中表示'), ('d', '下表示'), ('n', '非表示')], default='u', max_length=2, verbose_name='カテゴリ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
    ]
