# Generated by Django 3.1.3 on 2020-11-08 08:01

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0012_gift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=75, size=[200, 200], upload_to='static/images', verbose_name='URI'),
        ),
        migrations.CreateModel(
            name='CostPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('cost', models.IntegerField(verbose_name='料金')),
                ('extend_cost', models.IntegerField(verbose_name='延長料金')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basics.location', verbose_name='支店')),
            ],
        ),
    ]
