# Generated by Django 3.1.3 on 2020-12-22 19:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='目的')),
                ('give_amount', models.IntegerField(default=0, verbose_name='ポイント')),
                ('take_amount', models.IntegerField(default=0, verbose_name='ポイント')),
                ('reason', models.CharField(default='', max_length=190, verbose_name='理由')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('gift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basics.gift', verbose_name='ギフト')),
                ('giver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gave', to=settings.AUTH_USER_MODEL, verbose_name='使用')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'キャスト募集中'), (1, 'キャスト選択期間'), (2, '提案中'), (3, 'キャスト確定'), (4, '合流中'), (5, '合流完了'), (6, '完了（決済未完了'), (7, '決済完了'), (8, 'キャスト不足でキャンセル'), (9, '運営側キャンセル'), (10, '一般なエラー')], default=0, verbose_name='状態')),
                ('reservation', models.CharField(blank=True, max_length=100, null=True, verbose_name='予約名')),
                ('place', models.CharField(blank=True, max_length=100, null=True, verbose_name='予約場所')),
                ('meet_time', models.CharField(default='', max_length=50, verbose_name='合流時間')),
                ('meet_time_iso', models.DateTimeField(blank=True, null=True, verbose_name='ISO時間')),
                ('time_other', models.BooleanField(default=False, verbose_name='他時間')),
                ('location_other', models.CharField(blank=True, max_length=100, null=True, verbose_name='他の場所')),
                ('person', models.IntegerField(default=1, verbose_name='合流人数')),
                ('period', models.IntegerField(default=1, verbose_name='合流時間')),
                ('is_private', models.BooleanField(default=False, verbose_name='プライベート')),
                ('collect_started_at', models.DateTimeField(blank=True, null=True, verbose_name='キャスト募集開始時刻')),
                ('collect_ended_at', models.DateTimeField(blank=True, null=True, verbose_name='キャスト募集修了時刻')),
                ('ended_predict', models.DateTimeField(null=True, verbose_name='修了予定時刻')),
                ('ended_at', models.DateTimeField(null=True, verbose_name='修了時刻')),
                ('cost_value', models.IntegerField(default=0, verbose_name='料金')),
                ('cost_extended', models.IntegerField(default=0, verbose_name='延長料金')),
                ('final_cost', models.IntegerField(default=0, verbose_name='確定料金')),
                ('remark', models.TextField(null=True, verbose_name='備考')),
                ('operator_message', models.TextField(null=True, verbose_name='オペレーターメッセージ')),
                ('night_started_at', models.TimeField(blank=True, null=True, verbose_name='深夜料利用開始')),
                ('night_ended_at', models.TimeField(blank=True, null=True, verbose_name='深夜料利用修了')),
                ('night_fund', models.IntegerField(default=4000, verbose_name='深夜料')),
                ('night_back_ratio', models.IntegerField(default=0, verbose_name='深夜料バック率')),
                ('desire_cost', models.IntegerField(default=2000, verbose_name='指名料')),
                ('desire_back_ratio', models.IntegerField(default=0, verbose_name='指名料バック率')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='キャンセル')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='OK')),
                ('is_replied', models.BooleanField(default=False, verbose_name='応答')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('cost_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basics.costplan')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='with_child', to='basics.location')),
                ('parent_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='with_parent', to='basics.location')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='chat.room', verbose_name='チャットルーム')),
                ('situations', models.ManyToManyField(related_name='with_choice', to='basics.Choice', verbose_name='気持ち')),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asked', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='オーダー')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='スター')),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='calls.order', verbose_name='オーダー')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_targets', to=settings.AUTH_USER_MODEL, verbose_name='レビュー元')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_sources', to=settings.AUTH_USER_MODEL, verbose_name='レビュー先')),
            ],
        ),
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(null=True, verbose_name='開始時間')),
                ('ended_at', models.DateTimeField(null=True, verbose_name='修了時間')),
                ('status', models.IntegerField(choices=[(0, 'ドラフト'), (1, '確定')], default=0, verbose_name='状態')),
                ('selection', models.IntegerField(choices=[(0, 'キャスト募集'), (1, '優先マッチング')], default=0, verbose_name='選択')),
                ('dropped', models.BooleanField(default=False, verbose_name='却下')),
                ('is_started', models.BooleanField(default=False, verbose_name='開始')),
                ('is_ten_left', models.BooleanField(default=False, verbose_name='10分前')),
                ('is_extended', models.BooleanField(default=False, verbose_name='延長')),
                ('is_ended', models.BooleanField(default=False, verbose_name='修了')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joins', to='calls.order', verbose_name='チャットルーム')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joins', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_time', models.IntegerField(verbose_name='合流時間')),
                ('extend_point', models.IntegerField(default=0, verbose_name='延長ポイント')),
                ('extend_min', models.IntegerField(default=0, verbose_name='延長時間')),
                ('night_point', models.IntegerField(default=0, verbose_name='深夜ポイント')),
                ('desire_point', models.IntegerField(default=0, verbose_name='指名料金')),
                ('total_point', models.IntegerField(default=0, verbose_name='総合')),
                ('cast_point', models.IntegerField(default=0, verbose_name='キャストポイント')),
                ('cast_extend_point', models.IntegerField(default=0, verbose_name='キャスト延長ポイント')),
                ('cast_night_point', models.IntegerField(default=0, verbose_name='キャスト深夜ポイント')),
                ('cast_desire_point', models.IntegerField(default=0, verbose_name='キャスト指名ポイント')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('cast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_invoices', to=settings.AUTH_USER_MODEL, verbose_name='キャスト')),
                ('invoices', models.ManyToManyField(related_name='details', to='calls.Invoice', verbose_name='インボイス')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calls.order'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.room', verbose_name='ルーム'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='taker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='took', to=settings.AUTH_USER_MODEL, verbose_name='取得'),
        ),
    ]
