# Generated by Django 3.1.3 on 2020-11-19 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basics', '0013_auto_20201108_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='状態')),
                ('reservation', models.CharField(blank=True, max_length=100, null=True, verbose_name='予約名')),
                ('place', models.CharField(blank=True, max_length=100, null=True, verbose_name='予約場所')),
                ('meet_time', models.CharField(default='', max_length=50, verbose_name='合流時間')),
                ('meet_time_iso', models.CharField(default='', max_length=50, verbose_name='ISO時間')),
                ('time_other', models.BooleanField(default=False, verbose_name='他時間')),
                ('location_other', models.CharField(blank=True, max_length=100, null=True, verbose_name='他の場所')),
                ('person', models.IntegerField(default=1, verbose_name='合流人数')),
                ('period', models.IntegerField(default=1, verbose_name='合流時間')),
                ('is_private', models.BooleanField(default=False, verbose_name='プライベート')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('cast_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basics.costplan')),
                ('desired', models.ManyToManyField(related_name='invited', to=settings.AUTH_USER_MODEL, verbose_name='ご希望のキャスト')),
                ('joined', models.ManyToManyField(related_name='applied', to=settings.AUTH_USER_MODEL, verbose_name='応募者')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='with_child', to='basics.location')),
                ('parent_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='with_parent', to='basics.location')),
                ('situations', models.ManyToManyField(related_name='with_choice', to='basics.Choice', verbose_name='気持ち')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='オーダー')),
            ],
        ),
    ]
