# Generated by Django 3.1.3 on 2020-11-19 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cast_class',
            new_name='cost_plan',
        ),
    ]
