# Generated by Django 3.1.3 on 2020-11-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='reason',
            field=models.CharField(default='', max_length=190, verbose_name='理由'),
        ),
    ]
