# Generated by Django 3.1.3 on 2020-11-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0004_invoice_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='目的'),
        ),
    ]
