# Generated by Django 3.1.3 on 2020-11-24 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calls', '0005_auto_20201123_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='amount',
            new_name='give_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='user',
        ),
        migrations.AddField(
            model_name='invoice',
            name='giver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gave', to=settings.AUTH_USER_MODEL, verbose_name='使用'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='take_amount',
            field=models.IntegerField(default=0, verbose_name='ポイント'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='taker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='took', to=settings.AUTH_USER_MODEL, verbose_name='取得'),
        ),
    ]
