# Generated by Django 3.1.3 on 2020-11-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0006_auto_20201125_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'booked'), (1, 'reservation'), (2, 'suggest'), (3, 'confirm'), (4, 'starting'), (5, 'brokenUp'), (6, 'calculated')], default=0, verbose_name='状態'),
        ),
    ]
