# Generated by Django 3.1.3 on 2020-11-29 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_remove_room_order'),
        ('calls', '0007_auto_20201129_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='chat.room', verbose_name='チャットルーム'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'キャスト募集中'), (1, 'キャスト選択期間'), (2, '提案中'), (3, 'キャスト確定'), (4, '合流中'), (5, '合流完了'), (6, '完了（決済未完了'), (7, '決済完了'), (8, 'キャスト不足でキャンセル'), (9, '一般なエラー')], default=0, verbose_name='状態'),
        ),
    ]
