# Generated by Django 3.1.3 on 2020-12-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0010_auto_20201204_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='final_cost',
            field=models.IntegerField(default=0, verbose_name='確定料金'),
        ),
    ]
