# Generated by Django 3.1.3 on 2020-12-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0011_order_final_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='meet_time_iso',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ISO時間'),
        ),
    ]
