# Generated by Django 3.1.3 on 2020-12-04 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calls', '0012_auto_20201204_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='joined',
        ),
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(verbose_name='開始時間')),
                ('ended_at', models.DateTimeField(verbose_name='修了時間')),
                ('status', models.IntegerField(choices=[(0, 'ドラフト'), (1, '確定'), (4, '却下')], default=0, verbose_name='状態')),
                ('selection', models.IntegerField(choices=[(0, 'キャスト募集'), (1, '優先マッチング')], default=0, verbose_name='選択')),
                ('is_started', models.BooleanField(default=False, verbose_name='開始')),
                ('is_extended', models.BooleanField(default=False, verbose_name='延長')),
                ('is_fivepast', models.BooleanField(default=False, verbose_name='5分延長')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joins', to='calls.order', verbose_name='チャットルーム')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joins', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
    ]
