# Generated by Django 3.1.3 on 2020-12-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0013_auto_20201205_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='desire_back_ratio',
            field=models.IntegerField(default=0, verbose_name='指名料バック率'),
        ),
        migrations.AddField(
            model_name='order',
            name='desire_cost',
            field=models.IntegerField(default=2000, verbose_name='指名料'),
        ),
        migrations.AddField(
            model_name='order',
            name='night_back_ratio',
            field=models.IntegerField(default=0, verbose_name='深夜料バック率'),
        ),
    ]
