# Generated by Django 3.1.3 on 2020-12-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0017_auto_20201210_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='is_ten_left',
            field=models.BooleanField(default=False, verbose_name='10分前'),
        ),
    ]
