# Generated by Django 3.1.3 on 2020-12-11 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calls', '0019_remove_order_desired'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='OK'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='キャンセル'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_replied',
            field=models.BooleanField(default=False, verbose_name='応答'),
        ),
        migrations.AddField(
            model_name='order',
            name='point_half',
            field=models.IntegerField(default=0, verbose_name='時間単価'),
        ),
        migrations.AddField(
            model_name='order',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asked', to=settings.AUTH_USER_MODEL),
        ),
    ]
