# Generated by Django 3.1.3 on 2020-12-11 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0020_auto_20201212_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='point_half',
        ),
    ]
