# Generated by Django 3.1.3 on 2020-12-12 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calls', '0023_auto_20201212_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_time', models.IntegerField(verbose_name='合流時間')),
                ('extend_point', models.IntegerField(default=0, verbose_name='延長ポイント')),
                ('night_point', models.IntegerField(default=0, verbose_name='深夜ポイント')),
                ('desire_point', models.IntegerField(default=0, verbose_name='指名料金')),
                ('total_point', models.IntegerField(default=0, verbose_name='総合')),
                ('cast_point', models.IntegerField(default=0, verbose_name='キャストポイント')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('cast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_invoices', to=settings.AUTH_USER_MODEL, verbose_name='キャスト')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='calls.invoice', verbose_name='インボイス')),
            ],
        ),
    ]
