# Generated by Django 3.1.3 on 2020-12-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0025_auto_20201213_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetail',
            name='extend_min',
            field=models.IntegerField(default=0, verbose_name='延長時間'),
        ),
    ]
