# Generated by Django 3.1.3 on 2020-12-15 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0014_auto_20201215_2305'),
        ('calls', '0026_invoicedetail_extend_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='gift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basics.gift', verbose_name='ギフト'),
        ),
        migrations.AddField(
            model_name='invoicedetail',
            name='cast_desire_point',
            field=models.IntegerField(default=0, verbose_name='キャスト指名ポイント'),
        ),
        migrations.AddField(
            model_name='invoicedetail',
            name='cast_extend_point',
            field=models.IntegerField(default=0, verbose_name='キャスト延長ポイント'),
        ),
        migrations.AddField(
            model_name='invoicedetail',
            name='cast_night_point',
            field=models.IntegerField(default=0, verbose_name='キャスト深夜ポイント'),
        ),
        migrations.RemoveField(
            model_name='invoicedetail',
            name='invoice',
        ),
        migrations.AddField(
            model_name='invoicedetail',
            name='invoice',
            field=models.ManyToManyField(related_name='details', to='calls.Invoice', verbose_name='インボイス'),
        ),
    ]
