# Generated by Django 3.1.3 on 2020-12-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0027_auto_20201215_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicedetail',
            name='invoice',
        ),
        migrations.AddField(
            model_name='invoicedetail',
            name='invoices',
            field=models.ManyToManyField(related_name='details', to='calls.Invoice', verbose_name='インボイス'),
        ),
    ]
