# Generated by Django 3.1.3 on 2020-12-15 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_delete_suggestion'),
        ('calls', '0028_auto_20201215_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.room', verbose_name='ルーム'),
        ),
    ]
