# Generated by Django 3.1.3 on 2020-12-22 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basics', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_group', models.BooleanField(default=False, verbose_name='グループ')),
                ('last_message', models.TextField(blank=True, null=True, verbose_name='最後のメッセージ')),
                ('room_type', models.CharField(default='', max_length=30, verbose_name='タイプ')),
                ('title', models.CharField(blank=True, max_length=130, null=True, verbose_name='タイトル')),
                ('status', models.IntegerField(choices=[(0, 'default'), (1, 'suggest'), (2, 'confirm'), (3, 'end')], default=0, verbose_name='ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('last_sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_rooms', to=settings.AUTH_USER_MODEL, verbose_name='最後投稿者')),
                ('users', models.ManyToManyField(related_name='rooms', to=settings.AUTH_USER_MODEL, verbose_name='メンバー')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=100, verbose_name='内容')),
                ('notice_type', models.CharField(default='foot', max_length=100, verbose_name='タイプ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notices', to=settings.AUTH_USER_MODEL, verbose_name='通知元')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rececived_notices', to=settings.AUTH_USER_MODEL, verbose_name='通知先')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='コンテンツ')),
                ('is_read', models.BooleanField(default=False, verbose_name='読み済み')),
                ('is_notice', models.BooleanField(default=False, verbose_name='通知')),
                ('is_like', models.BooleanField(default=False, verbose_name='イイネ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('follower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.message', verbose_name='新メッセージ')),
                ('gift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basics.gift', verbose_name='ギフト')),
                ('medias', models.ManyToManyField(to='accounts.Media', verbose_name='画像')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.room', verbose_name='ルーム')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sended', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=190, verbose_name='タイトル')),
                ('content', models.TextField(blank=True, null=True, verbose_name='コンテンツ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basics.location', verbose_name='支店')),
            ],
        ),
    ]
