# Generated by Django 3.1.3 on 2020-11-19 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_like',
            field=models.BooleanField(default=False, verbose_name='イイネ'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(default='', max_length=30, verbose_name='タイプ'),
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=100, verbose_name='内容')),
                ('notice_type', models.CharField(default='foot', max_length=100, verbose_name='タイプ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notices', to=settings.AUTH_USER_MODEL, verbose_name='通知元')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rececived_notices', to=settings.AUTH_USER_MODEL, verbose_name='通知先')),
            ],
        ),
    ]
