# Generated by Django 3.1.3 on 2020-11-21 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_auto_20201120_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='joins',
        ),
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(verbose_name='開始時間')),
                ('is_extended', models.BooleanField(default=False, verbose_name='延長')),
                ('is_fivepast', models.BooleanField(default=False, verbose_name='5分延長')),
                ('ended_at', models.DateTimeField(verbose_name='修了時間')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joins', to='chat.room', verbose_name='チャットルーム')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joins', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
    ]
