# Generated by Django 3.1.3 on 2020-11-21 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_join_is_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='last_sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_rooms', to=settings.AUTH_USER_MODEL, verbose_name='最後投稿者'),
        ),
    ]
