# Generated by Django 3.1.3 on 2020-11-23 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0013_auto_20201108_1601'),
        ('chat', '0005_room_last_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=190, verbose_name='タイトル')),
                ('content', models.TextField(blank=True, null=True, verbose_name='コンテンツ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basics.location', verbose_name='支店')),
            ],
        ),
    ]
