# Generated by Django 3.1.3 on 2020-11-27 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_adminnotice'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='follower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.message', verbose_name='新メッセージ'),
        ),
    ]
