# Generated by Django 3.1.3 on 2020-11-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_message_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.IntegerField(choices=[(0, 'default')], default=0, verbose_name='ステータス'),
        ),
    ]
