# Generated by Django 3.1.3 on 2020-11-29 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_room_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='order',
        ),
    ]
