# Generated by Django 3.1.3 on 2020-12-04 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_remove_room_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Join',
        ),
    ]
