# Generated by Django 3.1.3 on 2020-12-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_delete_join'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.IntegerField(choices=[(0, 'default'), (1, 'suggest'), (2, 'confirm'), (3, 'end')], default=0, verbose_name='ステータス'),
        ),
    ]
