# Generated by Django 3.1.3 on 2020-12-10 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0013_auto_20201108_1601'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0011_auto_20201210_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meet_at', models.DateTimeField(verbose_name='日程')),
                ('period', models.IntegerField(default=1, verbose_name='時間')),
                ('point_half', models.IntegerField(verbose_name='時間単価')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='キャンセル')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='OK')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basics.location')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='chat.room')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
