# Generated by Django 3.1.3 on 2020-12-11 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0012_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested', to=settings.AUTH_USER_MODEL),
        ),
    ]
