# Generated by Django 3.1.3 on 2020-12-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_auto_20201211_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='is_replied',
            field=models.BooleanField(default=False, verbose_name='応答'),
        ),
    ]
