# Generated by Django 3.1.3 on 2020-12-11 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_suggestion_is_replied'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suggestion',
        ),
    ]
