# Generated by Django 3.1.3 on 2020-12-23 06:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='point_half',
            field=models.IntegerField(default=3000, validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(0)], verbose_name='30分あたりのポイント'),
        ),
    ]
