# Generated by Django 3.1.3 on 2020-11-03 07:28

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=75, size=[400, 400], upload_to='static/images', verbose_name='URI')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='avatar',
        ),
        migrations.AddField(
            model_name='member',
            name='avatars',
            field=models.ManyToManyField(related_name='avatar', to='accounts.Media', verbose_name='アバタ'),
        ),
    ]
