# Generated by Django 3.1.3 on 2020-11-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201106_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='images',
            field=models.ManyToManyField(to='accounts.Media', verbose_name='画像'),
        ),
    ]
