# Generated by Django 3.1.3 on 2020-11-07 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201107_0258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, null=True, verbose_name='自己紹介')),
                ('residence', models.CharField(blank=True, max_length=100, null=True, verbose_name='居住地')),
                ('birthplace', models.CharField(blank=True, max_length=100, null=True, verbose_name='出身地')),
                ('qualification', models.IntegerField(choices=[(0, '未定'), (1, '中卒'), (2, '高卒'), (3, '大卒'), (4, '大学院卒'), (5, '専門卒'), (6, 'その他')], default=0, verbose_name='学歴')),
                ('annual', models.IntegerField(choices=[(0, '未定'), (1, '中卒'), (2, '高卒'), (3, '大卒'), (4, '大学院卒'), (5, '専門卒'), (6, 'その他')], default=0, verbose_name='学歴')),
                ('job', models.CharField(blank=True, max_length=100, null=True, verbose_name='お仕事')),
                ('favorite', models.CharField(blank=True, max_length=100, null=True, verbose_name='よく飲む地域')),
                ('drink', models.CharField(blank=True, max_length=100, null=True, verbose_name='お酒')),
                ('sibling', models.CharField(blank=True, max_length=100, null=True, verbose_name='兄弟姉妹')),
                ('smoke', models.CharField(blank=True, max_length=100, null=True, verbose_name='タバコ')),
                ('language', models.CharField(blank=True, max_length=100, null=True, verbose_name='外国語')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='身長')),
                ('guest_style', models.IntegerField(choices=[(0, '未定'), (1, '細身'), (2, '普通'), (3, 'ガッチリ'), (4, 'ぽっちゃり'), (5, '太め')], default=0, verbose_name='ゲストスタイル')),
                ('cast_style', models.IntegerField(choices=[(0, '未定'), (1, '細身'), (2, '普通'), (3, 'グラマラス')], default=0, verbose_name='キャストスタイル')),
                ('hair', models.CharField(blank=True, max_length=100, null=True, verbose_name='髪色・髪型')),
                ('entertainment', models.CharField(blank=True, max_length=100, null=True, verbose_name='似ている芸能人')),
                ('charm', models.CharField(blank=True, max_length=100, null=True, verbose_name='チャームポイント')),
                ('girl_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='好きな女性のタイプ')),
                ('costume', models.CharField(blank=True, max_length=100, null=True, verbose_name='好きな服装')),
                ('dislike', models.CharField(blank=True, max_length=100, null=True, verbose_name='こういうタイプはNG')),
                ('character', models.CharField(blank=True, max_length=100, null=True, verbose_name='性格')),
                ('talk_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='話し上手？聞き上手？')),
                ('want_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='こんな話を話したい・聞きたい')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.detail'),
        ),
    ]
