# Generated by Django 3.1.3 on 2020-11-07 21:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201108_0331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='about',
        ),
        migrations.AddField(
            model_name='member',
            name='video_point_half',
            field=models.IntegerField(default=3000, validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(1000)], verbose_name='ビデオオーダー料金'),
        ),
    ]
