# Generated by Django 3.1.3 on 2020-11-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20201108_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='category',
            field=models.IntegerField(choices=[(0, '全て'), (1, 'キャストのみ')], default=0, verbose_name='キャストのみ'),
        ),
    ]
