# Generated by Django 3.1.3 on 2020-11-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_tweet_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='housemate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='同居人'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='annual',
            field=models.IntegerField(choices=[(0, '未定'), (1, '500万以下'), (2, '500万～1000万'), (3, '1000万～1500万'), (4, '1500万～2000万'), (5, '2000万～3000万'), (6, '3000万～5000万'), (7, '5000万～1億'), (8, '1億以上')], default=0, verbose_name='学歴'),
        ),
    ]
