# Generated by Django 3.1.3 on 2020-11-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20201111_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='residence',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='居住地'),
        ),
    ]
