# Generated by Django 3.1.3 on 2020-11-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20201111_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='about',
            field=models.TextField(blank=True, default='', null=True, verbose_name='自己紹介'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='birthplace',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='出身地'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='character',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='性格'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='charm',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='チャームポイント'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='costume',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='好きな服装'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='dislike',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='こういうタイプはNG'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='drink',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='お酒'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='entertainment',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='似ている芸能人'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='favorite',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='よく飲む地域'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='girl_type',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='好きな女性のタイプ'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='hair',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='髪色・髪型'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='height',
            field=models.CharField(blank=True, default='', max_length=3, null=True, verbose_name='身長'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='housemate',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='同居人'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='job',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='お仕事'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='language',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='外国語'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='sibling',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='兄弟姉妹'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='smoke',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='タバコ'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='talk_type',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='話し上手？聞き上手？'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='want_type',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='こんな話を話したい・聞きたい'),
        ),
    ]
