# Generated by Django 3.1.3 on 2020-11-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20201111_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='cast_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='キャスト登録日時'),
        ),
        migrations.AddField(
            model_name='member',
            name='guest_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ゲスト登録日時'),
        ),
        migrations.AddField(
            model_name='member',
            name='left_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='オフライン日時'),
        ),
    ]
