# Generated by Django 3.1.3 on 2020-11-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0013_auto_20201108_1601'),
        ('accounts', '0015_auto_20201112_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='cast_status',
            field=models.ManyToManyField(to='basics.Choice', verbose_name='キャストステータス'),
        ),
    ]
