# Generated by Django 3.1.3 on 2020-11-16 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0013_auto_20201108_1601'),
        ('accounts', '0019_delete_caststatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='introducer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intros', to=settings.AUTH_USER_MODEL, verbose_name='紹介者'),
        ),
        migrations.CreateModel(
            name='TransferInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(default='', max_length=190, verbose_name='銀行名')),
                ('rank_no', models.CharField(default='', max_length=190, verbose_name='金融機関番号')),
                ('site_name', models.CharField(default='', max_length=190, verbose_name='支店名')),
                ('site_no', models.CharField(default='', max_length=190, verbose_name='支店番号')),
                ('account_no', models.CharField(default='', max_length=190, verbose_name='口座番号')),
                ('account_cat', models.IntegerField(choices=[(0, '通常'), (1, '当座')], default=0, verbose_name='口座種別')),
                ('transfer_name', models.CharField(default='', max_length=190, verbose_name='名義')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_infos', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='TransferApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '未処理'), (1, '処理済み')], default=0, verbose_name='ステータス')),
                ('amount', models.IntegerField(default=0, verbose_name='現金')),
                ('apply_type', models.IntegerField(choices=[(0, '通常入金'), (1, 'すぐ入金')], verbose_name='種別')),
                ('currency_type', models.CharField(default='', max_length=190, verbose_name='通貨種別')),
                ('point', models.IntegerField(default=0, verbose_name='ポイント')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申請日時')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basics.location', verbose_name='支店')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_applications', to=settings.AUTH_USER_MODEL, verbose_name='対象者')),
            ],
        ),
    ]
