# Generated by Django 3.1.3 on 2020-11-16 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_channel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Channel',
        ),
    ]
