# Generated by Django 3.1.3 on 2020-11-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20201118_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='inviter_code',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True, verbose_name='紹介者コード'),
        ),
        migrations.AlterField(
            model_name='member',
            name='nickname',
            field=models.CharField(blank=True, max_length=190, null=True, verbose_name='ニックネーム'),
        ),
    ]
