# Generated by Django 3.1.3 on 2020-11-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20201118_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='プロフィール公開'),
        ),
    ]
