# Generated by Django 3.1.3 on 2020-11-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20201122_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_introducer',
            field=models.BooleanField(default=False, verbose_name='紹介者'),
        ),
    ]
