# Generated by Django 3.1.3 on 2020-11-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_member_is_introducer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='cast_started_at',
        ),
        migrations.RemoveField(
            model_name='member',
            name='guest_started_at',
        ),
        migrations.AddField(
            model_name='member',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='登録日時'),
        ),
    ]
