# Generated by Django 3.1.3 on 2020-12-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_auto_20201127_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='back_ratio',
            field=models.IntegerField(default=75, verbose_name='バック率'),
        ),
    ]
