# Generated by Django 3.1.3 on 2020-12-12 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20201205_2146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
